project:
  type: website
  output-dir: docs

bibliography: references.bib

format:
  html:
    title: "ML From Scratch: Implementasi di balik layar"
    author: "Aria Ghora Prabono"
    date: "6/30/2022"
    cover-image: cover.png
    toc: true
    html-math-method: katex
    theme: cosmo
    standalone: true
    self-contained: true
    crossref:
      fig-title: Gambar
      fig-prefix: ""
      eq-prefix: ""

website:
  sidebar:
    style: docked
    contents:
      - text: Pendahuluan
        file: pendahuluan.qmd
      - text: Struktur data n-dimensional array
        file: ndarray.qmd
