project:
  type: website
  output-dir: docs

bibliography: references.bib

format:
  html:
    title: "ML From Scratch: Implementasi di balik layar"
    cover-image: cover.png
    toc: true
    html-math-method: katex
    theme: cosmo
    standalone: true
    self-contained: true
    crossref:
      fig-title: Gambar
      fig-prefix: ""
      eq-prefix: ""

website:
  sidebar:
    style: floating
    search: false
    title: ML From Scratch
    subtitle: implementasi di balik layar
    alignment: center
    contents:
      - text: Muka
        file: index.qmd
      - text: Pendahuluan
        file: pendahuluan.qmd
      - text: Struktur data n-dimensional array
        file: ndarray.qmd
  page-footer:
    left: "Copyright 2022, Aria Ghora Prabono"
    right:
      - icon: twitter
        href: https://twitter.com/aria_ghora
      - icon: github
        href: https://github.com/ariaghora
