# Pendahuluan 

## Machine learning

_Machine learning_, atau dalam Bahasa Indonesianya _pembelajaran mesin_, adalah cabang dari disiplin ilmu kecerdasan buatan yang berfokus membangun sistem cerdas yang mampu belajar dari data.

@mitchell1997machine memberikan definisi singkat dari _learning_ (atau "belajar", dalam konteks algoritma pembelajaran), yaitu:

> "Suatu program komputer dikatakan 'belajar' dari pengalaman (_experience_) $E$ pada tugas (_task_) $T$ yang performanya terukur dengan ukuran $P$."

### Pengalaman (_experience_) $E$
Algoritma pembelajaran belajar dari pengalaman, dan pengalaman yang dimaksud adalah **dataset**.
Secara umum dapat dibagi setidaknya dua kategori: **_supervised learning_** dan **_unsupervised learning_**.

- **_Supervised learning_** adalah pembelajaran dengan dataset yang disertai label/target yang diketahui.
- **_Unsupervised learning_** adalah pembelajaran dengan dataset yang tidak disertai label/target.

Kita akan lebih banyak fokus pada _supervised learning_.

### Tugas (_task_) $T$ dalam _supervised learning_
Ada beberapa jenis tugas yang dapat dilakukan dengan _machine learning_ pada suatu program komputer.
Antara lain:

- Regresi (_regression_): algoritma pembelajaran akan mempelajari suatu fungsi $f:\mathbb{R}^n\rightarrow\mathbb{R}$.
  Dengan kata lain, pada tugas ini, suatu program komputer diminta untuk memprediksi nilai numerik berdasarkan suatu input.
- Klasifikasi (_classification_): algoritma pembelajaran akan mempelajari $f:\mathbb{R}^n\rightarrow\{1, ..., k\}$.
  Pada tugas ini, suatu program komputer diminta untuk menentukan kelas dari suatu data.

### Performa $P$
Performa adalah ukuran dari hasil yang diberikan oleh algoritma pembelajaran. 
Misalnya, untuk klasifikasi, salah satu performa yang dapat dijadikan acuan adalah akurasi dari suatu model.
Akurasi diperoleh dari persentase prediksi yang benar dari data yang diberikan.


## Implementasi di balik layar
Maksud dari di balik layar ialah implementasi berbagai aspek _machine learning_ yang terjadi di balik layar dari awal, dengan sedikit (hingga tanpa) _library_ tambahan.
Walau implementasi dilakukan mulai awal, secara bertahap pembaca akan diperkenalkan dengan _library_ tambahan yang penting.

Mengapa harus _from scratch_ sementara sudah ada banyak pustaka di luar sana (NumPy, scikit-learn, PyTorch, dan lainnya)? 
Mengutip @grus2019data:

> Langsung menggunakan pustaka \textit{data science} adalah cara yang bagus untuk memulai melakukan _data science_ tanpa memahami _data science_ itu sendiri. 

Penulis meyakini bahwa hal itu juga berlaku pada _machine learning_.
Cara terbaik untuk menggunakan pustaka _machine learning_ secara efektif dan komprehensif adalah dengan mengalami proses pembuatannya sendiri.
Kita tidak menargetkan untuk membuat implementasi yang paling efektif, tetapi kita akan fokus pada pemahaman cara kerja pustaka _machine learning_ di balik layar.

## Konvensi

Bagian yang memerlukan perhatian khusus akan dicetak dengan format kotak berwarna biru seperti di bawah ini.

:::{.callout-note}
### Catatan
Isi pesan catatan di sini	
:::

Kadang kala ada tips dan trik yang mungkin membantu pembaca.
Bagian ini akan dicetak dengan kotak berwarna hijau seperti berikut.

:::{.callout-tip}
### Tips
Isi pesan tips di sini	
:::

Potongan kode atau bagian kode dalam paragraf (_inline_) dicetak dengan font `monospaced`.
Blok kode diformat dengan _syntax highlighting_ seperti berikut ini.

```{python}
#| eval: false
import numpy as np

print("Hai")
fruits = ["banana", "apple", "orange"]

for fruit in fruits:
	print(fruit)
```

Kadang potongan kode juga akan disertai _output_ yang akan dicetak di bawahnya.

```{python}
a = 10
b = 20
print("Hasil penjumlahan:", a + b)
```

## Notasi matematika
Demi konsistensi, penulis menetapkan konvensi penulisan notasi matematika.
Variabel bernilai skalar dinotasikan dengan aksara Latin atau Yunani non-kapital cetak miring, seperti $x$, $y$, $\alpha$, atau $\beta$.
Vektor dinotasikan dengan aksara Latin atau Yunani non-kapital cetak tebal $\mathbf{x}$, $\mathbf{y}$.
Elemen skalar ke-$i$ dari vektor $\mathbf{x}$ dinotasikan dengan $x_i$.
Matriks dinotasikan dengan aksara Latin atau Yunani kapital cetak tebal $\mathbf{X}$, $\mathbf{Y}$, $\mathbf{\Sigma}$ 
Elemen baris ke-$i$ kolom ke-$j$ suatu matriks $\mathbf{X}$ dinotasikan dengan $x_{i,j}$.
Himpunan (_set_) dinotasikan dengan huruf yang dicetak kaligrafis, seperti $\mathcal{X}$, $\mathcal{S}$, atau $\mathcal{L}$.
Himpunan bilangan riil dinotasikan dengan $\mathbb{R}$.
Matriks $\mathbf{X}$ dari himpunan bilangan riil berukuran $m \times n$ kadang dinotasikan dengan $\mathbf{X}\in\mathbb{R}^{m \times n}$.
